[build]
  command = "npm run netlify:build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20.18.0"
  NPM_VERSION = "10.2.4"

[[headers]]
  for = "/*"
  values = {Referrer-Policy = "strict-origin-when-cross-origin", X-Content-Type-Options = "nosniff"}

# Redirects for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Domain redirects
[[redirects]]
  from = "https://deletemydata.netlify.app/*"
  to = "https://deletemydata.online/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.deletemydata.netlify.app/*"
  to = "https://deletemydata.online/:splat"
  status = 301
  force = true 