[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20.18.0"

# SPA fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Domain redirects - redirect from Netlify to main domain
[[redirects]]
  from = "https://magnificent-twilight-6a72c6.netlify.app/*"
  to = "https://deletemydata.online/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.magnificent-twilight-6a72c6.netlify.app/*"
  to = "https://deletemydata.online/:splat"
  status = 301
  force = true 